name: mongodb-replicacion
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pandas=2.3.1
  - numpy=2.2.6
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - requests=2.32.4
  - jupyter
  - jupyterlab=4.4.4
  - notebook
  - ipykernel
  - pymongo=4.13.2
  - dnspython
  - python-dateutil
  - tqdm
  - scipy
  - scikit-learn
  - plotly
  - pathlib2
  - wordcloud
  - folium
