version: '3.8'

services:
  mongo-primary:
    image: mongo:6.0
    container_name: mongo-primary
    restart: always
    ports:
      - "27020:27017"
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo_primary_data:/data/db
    networks:
      - mongo-network

  mongo-secondary1:
    image: mongo:6.0
    container_name: mongo-secondary1
    restart: always
    ports:
      - "27021:27017"
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo_secondary1_data:/data/db
    networks:
      - mongo-network

  mongo-secondary2:
    image: mongo:6.0
    container_name: mongo-secondary2
    restart: always
    ports:
      - "27022:27017"
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo_secondary2_data:/data/db
    networks:
      - mongo-network

volumes:
  mongo_primary_data:
  mongo_secondary1_data:
  mongo_secondary2_data:

networks:
  mongo-network:
    driver: bridge

